---
- hosts: servers #mention the host group name
  remote_user: ubuntu
  become: yes
  vars:
    ansible_ssh_private_key_file: "key file yourpath"
  roles:
    - nginx
    - docker
    - java
    - mysql
