---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install Java
  apt:
    name: "{{ java_package }}"
    state: present

- name: Verify Java installation
  command: java -version
  register: java_version_output
  changed_when: no

- name: Print Java version
  debug:
    msg: "{{ java_version_output.stdout }}"
