---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ docker_package }}"
    state: present

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

